Repository 42-Short/shortinette, pull requests merged in 2024-11, with the labels that each got.

#147 Update rust module01 mandatory
  rust/subjects/module-01.md
Labels: enhancement

#146 Improve Rust Module 00 Mandatory
  rust/subjects/module-00.md
Labels: enhancement

#173 Jakobus42/feat/db
  app/db/dao.go
  app/db/dao_test.go
  app/db/data.go
  app/db/db.go
  app/db/db_test.go
  app/db/db_test_setup.go
  app/db/schema.sql
  app/go.mod
  app/go.sum
Labels: db

#177 refactor: new file structure
  app/data/dao.go
  app/data/dao_test.go
  app/data/data.go
  app/db/db.go
  app/db/db_test.go
  app/db/db_test_setup.go
Labels: backend, db

#176 Jakobus42/feat/logger
  app/data/dao_test.go
  app/db/db.go
  app/git/git.go
  app/go.mod
  app/go.sum
  app/logger/logger.go
  app/main.go
Labels: package, backend
